In [1]:
import pandas as pd
import numpy as np

In [2]:
df_ue = pd.read_csv('../Datasets/amari_ue_data.csv')

In [3]:
df_ue.head()

,timestamp,imeisv,5g_tmsi,amf_ue_id,bearer_0_apn,bearer_0_dl_total_bytes,bearer_0_ip,bearer_0_ipv6,bearer_0_pdu_session_id,bearer_0_qos_flow_id,...,ran_ue_id,registered,rnti,t3512,tac,tac_plmn,ue_aggregate_max_bitrate_dl,ue_aggregate_max_bitrate_ul,ul_bitrate,cell_id
0,2024-01-24 14:00:00+00:00,3557821101183501,7.742631e+08,22037.0,ims,25334149.0,192.168.4.22,2001:468:3000:6::,1.0,1.0,...,21961.0,True,39881.0,1800.0,100.0,101.0,5.000000e+09,2.000000e+09,2403.0,1.0
1,2024-01-24 14:00:00+00:00,8609960468879056,3.766916e+09,22039.0,internet,40884332.0,10.20.10.24,NaN,6.0,1.0,...,21963.0,True,39883.0,1800.0,100.0,101.0,5.000000e+09,2.000000e+09,9271.0,1.0
2,2024-01-24 14:00:00+00:00,8609960480666910,2.495735e+08,11588.0,internet,103002274.0,10.20.10.20,NaN,5.0,1.0,...,11490.0,True,29410.0,1800.0,100.0,101.0,5.000000e+09,2.000000e+09,1513.0,1.0
3,2024-01-24 14:00:00+00:00,8609960480859056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-24 14:00:00+00:00,8628490433231156,1.232076e+09,22035.0,ims,89786.0,192.168.4.18,2001:468:3000:5::,13.0,1.0,...,21958.0,True,39878.0,1800.0,100.0,101.0,5.000000e+09,2.000000e+09,3055.0,1.0

In [4]:
features_to_remove = ['5g_tmsi', 'amf_ue_id', 'bearer_0_apn', 'bearer_0_ip',
                      'bearer_0_ipv6', 'bearer_0_pdu_session_id',
                      'bearer_0_qos_flow_id', 'bearer_0_sst', 'bearer_1_apn',
                      'bearer_1_ip', 'bearer_1_ipv6', 'bearer_1_pdu_session_id',
                      'bearer_1_qos_flow_id', 'bearer_1_sst', 'cell_X_cell_id',
                      'ran_plmn', 'registered', 'rnti', 't3512', 'tac',
                      'tac_plmn', 'ue_aggregate_max_bitrate_dl',
                      'ue_aggregate_max_bitrate_ul', 'dl_bitrate','ul_bitrate',
                      'ran_id', 'ran_ue_id', 'cell_X_ri']
df_ue = df_ue.drop(columns=features_to_remove)
df_ue['timestamp'] = pd.to_datetime(df_ue['timestamp'])
df_ue = df_ue.sort_values(by=['imeisv', 'timestamp'])
df_ue.head()

,timestamp,imeisv,bearer_0_dl_total_bytes,bearer_0_ul_total_bytes,bearer_1_dl_total_bytes,bearer_1_ul_total_bytes,cell_X_cqi,cell_X_dl_bitrate,cell_X_dl_mcs,cell_X_dl_retx,...,cell_X_turbo_decoder_avg,cell_X_turbo_decoder_max,cell_X_turbo_decoder_min,cell_X_ul_bitrate,cell_X_ul_mcs,cell_X_ul_path_loss,cell_X_ul_phr,cell_X_ul_retx,cell_X_ul_tx,cell_id
0,2024-01-24 14:00:00+00:00,3557821101183501,25334149.0,4198253.0,33905782.0,33364678.0,14.0,5887.0,21.8,3.0,...,2.273,4.0,2.0,2403.0,4.2,73.2,38.0,0.0,11.0,1.0
18,2024-01-24 14:00:05+00:00,3557821101183501,25334149.0,4198253.0,33906202.0,33365098.0,15.0,5718.0,21.8,6.0,...,2.300,3.0,2.0,2192.0,4.0,72.7,38.0,0.0,10.0,1.0
28,2024-01-24 14:00:10+00:00,3557821101183501,25334149.0,4198253.0,33906622.0,33365518.0,14.0,5492.0,21.7,5.0,...,2.300,3.0,1.0,2194.0,4.0,72.4,38.0,0.0,10.0,1.0
38,2024-01-24 14:00:15+00:00,3557821101183501,25334149.0,4198253.0,33907042.0,33365938.0,14.0,6091.0,22.0,6.0,...,2.100,3.0,2.0,2189.0,4.0,71.7,38.0,0.0,10.0,1.0
49,2024-01-24 14:00:20+00:00,3557821101183501,25334149.0,4198253.0,33907462.0,33366358.0,14.0,5765.0,21.9,5.0,...,1.800,2.0,1.0,2189.0,4.0,71.8,38.0,0.0,10.0,1.0

In [5]:
# print how many Nan values exist in each column
nan_counts = df_ue.isnull().sum()
for column, count in nan_counts.items():
    print(f"Column '{column}': {count} NaN values")

Column 'timestamp': 0 NaN values
Column 'imeisv': 0 NaN values
Column 'bearer_0_dl_total_bytes': 14661 NaN values
Column 'bearer_0_ul_total_bytes': 14661 NaN values
Column 'bearer_1_dl_total_bytes': 70305 NaN values
Column 'bearer_1_ul_total_bytes': 70305 NaN values
Column 'cell_X_cqi': 14661 NaN values
Column 'cell_X_dl_bitrate': 14661 NaN values
Column 'cell_X_dl_mcs': 15084 NaN values
Column 'cell_X_dl_retx': 14661 NaN values
Column 'cell_X_dl_tx': 14661 NaN values
Column 'cell_X_epre': 14661 NaN values
Column 'cell_X_initial_ta': 14661 NaN values
Column 'cell_X_p_ue': 14661 NaN values
Column 'cell_X_pusch_snr': 14661 NaN values
Column 'cell_X_turbo_decoder_avg': 16595 NaN values
Column 'cell_X_turbo_decoder_max': 16595 NaN values
Column 'cell_X_turbo_decoder_min': 16595 NaN values
Column 'cell_X_ul_bitrate': 14661 NaN values
Column 'cell_X_ul_mcs': 16590 NaN values
Column 'cell_X_ul_path_loss': 14661 NaN values
Column 'cell_X_ul_phr': 14661 NaN values
Column 'cell_X_ul_retx': 14661 NaN values
Column 'cell_X_ul_tx': 14661 NaN values
Column 'cell_id': 14661 NaN values

In [6]:
# Remove rows where only the first two features have values
print("Number of instances before: ",len(df_ue))
df_ue = df_ue[df_ue.iloc[:, 2:].notna().any(axis=1)].reset_index(drop=True)
print("Number of instances after: ",len(df_ue))

Number of instances before:  194400
Number of instances after:  179739

In [7]:
# print how many Nan values exist in each column
nan_counts = df_ue.isnull().sum()
for column, count in nan_counts.items():
    print(f"Column '{column}': {count} NaN values")

Column 'timestamp': 0 NaN values
Column 'imeisv': 0 NaN values
Column 'bearer_0_dl_total_bytes': 0 NaN values
Column 'bearer_0_ul_total_bytes': 0 NaN values
Column 'bearer_1_dl_total_bytes': 55644 NaN values
Column 'bearer_1_ul_total_bytes': 55644 NaN values
Column 'cell_X_cqi': 0 NaN values
Column 'cell_X_dl_bitrate': 0 NaN values
Column 'cell_X_dl_mcs': 423 NaN values
Column 'cell_X_dl_retx': 0 NaN values
Column 'cell_X_dl_tx': 0 NaN values
Column 'cell_X_epre': 0 NaN values
Column 'cell_X_initial_ta': 0 NaN values
Column 'cell_X_p_ue': 0 NaN values
Column 'cell_X_pusch_snr': 0 NaN values
Column 'cell_X_turbo_decoder_avg': 1934 NaN values
Column 'cell_X_turbo_decoder_max': 1934 NaN values
Column 'cell_X_turbo_decoder_min': 1934 NaN values
Column 'cell_X_ul_bitrate': 0 NaN values
Column 'cell_X_ul_mcs': 1929 NaN values
Column 'cell_X_ul_path_loss': 0 NaN values
Column 'cell_X_ul_phr': 0 NaN values
Column 'cell_X_ul_retx': 0 NaN values
Column 'cell_X_ul_tx': 0 NaN values
Column 'cell_id': 0 NaN values

In [8]:
# save the rows with the nan values

# Identify rows with NaN values in any of the columns except the first one
nan_rows = df_ue[df_ue.iloc[:, 1:].isna().any(axis=1)]

# Save the rows with NaN values to a CSV file
nan_rows.to_csv('nan_rows.csv', index=False)

In [9]:
# replace nan values to zero 
df_ue['cell_X_dl_mcs'] = df_ue['cell_X_dl_mcs'].fillna(0)
df_ue['bearer_1_dl_total_bytes'] = df_ue['bearer_1_dl_total_bytes'].fillna(0)
df_ue['bearer_1_ul_total_bytes'] = df_ue['bearer_1_ul_total_bytes'].fillna(0)
df_ue['cell_X_turbo_decoder_avg'] = df_ue['cell_X_turbo_decoder_avg'].fillna(0)
df_ue['cell_X_turbo_decoder_max'] = df_ue['cell_X_turbo_decoder_max'].fillna(0)
df_ue['cell_X_turbo_decoder_min'] = df_ue['cell_X_turbo_decoder_min'].fillna(0)

In [10]:
# remove cell_X_ul_mcs
df_ue = df_ue.drop(columns = ['cell_X_ul_mcs'])

In [11]:
# save new dataframe
df_ue.to_csv('ue_data_new.csv',index=False)